#ifndef		MSG_H
# define	MSG_H
 
typedef enum		e_msg
{
	MSG_CO_CONFIRM, MSG_CO_WAIT, MSG_CO_DISCO,
	MSG_COMMAND_ERROR,
	MSG_FILE_NOT_EXISTS,
	MSG_FILE_GET, MSG_FILE_GET_CONFIRM, MSG_FILE_GET_USAGE, MSG_FILE_GET_ERR,
	MSG_FILE_PUT, MSG_FILE_PUT_CONFIRM, MSG_FILE_PUT_USAGE, MSG_FILE_PUT_ERR,
	MSG_LS,
	MSG_PWD,
	MSG_CD, MSG_CD_NO_SUCH_FILE, MSG_CD_ACCESS_DENIED
}					t_msg;

#endif