#ifndef		MSG_H
# define	MSG_H
 
typedef enum		e_msg
{
	MSG_CO_CONFIRM, MSG_CO_WAIT, MSG_CO_DISCO,
	MSG_CO_COMMAND_OK, MSG_COMMAND_ERROR,
	MSG_FILE_NOT_EXISTS,
	MSG_FILE_GET, MSG_FILE_GET_CONFIRM, MSG_FILE_GET_USAGE,
	MSG_FILE_PUT, MSG_FILE_PUT_CONFIRM, MSG_FILE_PUT_USAGE
}					t_msg;

#endif